name: Sync to GitLab

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to GitLab
      run: |
        git remote add gitlab git@35.241.87.36:sean/testpr.git
        git push --all gitlab
